export const recipeData = {
  1: {
    title: "One-pan chicken curry 🍛",
    ingredients: [
      "750g chicken thighs",
      "3 onions, chopped",
      "2 garlic cloves",
      "2 tsp ginger, grated",
      "400ml coconut milk",
      "1 tbsp curry powder",
      "1 tbsp olive oil",
      "Salt and pepper to taste",
      "Fresh coriander (optional)",
    ],
    instructions: [
      "Heat oil in a large pan over medium heat.",
      "Add chopped onions and garlic, sauté until translucent.",
      "Add grated ginger and curry powder, cook for 2 minutes.",
      "Add chicken thighs and brown on all sides.",
      "Pour in coconut milk, bring to a simmer.",
      "Cover and cook for 25-30 minutes until chicken is cooked through.",
      "Season with salt and pepper.",
      "Garnish with fresh coriander if desired and serve.",
    ],
  },
  2: {
    title: "Chocolate chip cookies 🍪",
    ingredients: [
      "100g spelt flour",
      "100g almond flour",
      "100g butter",
      "75g honey",
      "1 tsp baking powder",
      "1 tsp vanilla extract",
      "50g chocolate chips",
    ],
    instructions: [
      "Preheat the oven to 180 degrees Celsius.",
      "Mix butter and honey until creamy.",
      "Add flours, baking powder and vanilla, mix well.",
      "Fold in chocolate chips.",
      "Scoop dough on baking tray lined with parchment.",
      "Bake for 10-12 minutes or until golden.",
      "Let cool before eating.",
    ],
  },
  3: {
    title: "Gingerbread coffee cake ☕️🧁",
    ingredients: [
      "200g flour",
      "120g honey",
      "50g butter",
      "2 eggs",
      "1 tsp baking powder",
      "1 tsp gingerbread spice",
      "1 tsp vanilla extract",
      "100ml milk",
    ],
    instructions: [
      "Preheat oven to 180 degrees Celsius.",
      "Mix all ingredients until smooth.",
      "Pour into a lined baking tin.",
      "Bake for 35-40 minutes until a toothpick comes out clean.",
      "Cool before serving.",
    ],
  },
  4: {
    title: "Healthy tiramisu 😋",
    ingredients: [
      "200g mascarpone",
      "200ml thickened cream",
      "1 shot espresso",
      "1 tbsp honey (optional)",
      "150g ladyfingers",
      "2 tsp cocoa powder",
    ],
    instructions: [
      "Beat cream for 30 seconds, add mascarpone and beat until peaks form.",
      "Fold in espresso and honey.",
      "Layer ladyfingers, cream mixture, repeat layers.",
      "Dust with cocoa powder.",
      "Chill for at least 2 hours before serving.",
    ],
  },
  5: {
    title: "Easy almond cookies 🍪",
    ingredients: [
      "112g almond flour",
      "45g honey",
      "30ml almond milk (or any plant-based milk)",
      "1 tsp vanilla extract",
      "1 tsp almond extract",
      "Unsalted almonds (for topping)",
    ],
    instructions: [
      "Preheat oven to 180 degrees and line oven dish with parchment paper.",
      "Combine almond flour, honey, milk, vanilla extract, and almond extract until dough forms.",
      "Roll tablespoon-sized dough balls, place on parchment paper.",
      "Flatten cookies, add an almond on top.",
      "Bake for 10-12 minutes at 180 degrees.",
      "Cool completely before eating.",
    ],
  },
  6: {
    title: "Brownie-tiramisu 🍫",
    ingredients: [
      "90g butter",
      "180g dark chocolate",
      "2 eggs",
      "1 tsp vanilla extract",
      "1/2 tsp vanilla powder",
      "100g honey",
      "1 shot espresso",
      "30g spelt flour",
      "90g almond flour",
      "200ml thickened cream",
      "200g mascarpone",
      "1 shot espresso",
      "1 tbsp honey (optional)",
      "Cacao powder for dusting",
    ],
    instructions: [
      "Preheat oven to 180 degrees.",
      "Melt butter and chocolate, stir until combined.",
      "Mix in eggs, vanilla extract, vanilla powder, espresso, honey, spelt and almond flour.",
      "Pour into parchment-lined dish and bake for 25-30 minutes until toothpick is almost clean.",
      "Beat cream for 30 seconds, add mascarpone and beat until peaks form.",
      "Fold in espresso and optional honey.",
      "Top brownies with espresso cream, refrigerate to cool.",
      "Dust with cacao powder before serving.",
    ],
  },
  7: {
    title: "No bake date cake 🧁",
    ingredients: [
      "250g dates",
      "125g butter",
      "50g walnuts and/or pecans",
      "1 tbsp honey",
      "100g sugar-free biscuits",
    ],
    instructions: [
      "Add dates and nuts to a food processor.",
      "Chop biscuits into small pieces.",
      "Melt butter on low heat, add honey, dates and nuts, stir well and heat 1 minute more.",
      "Add biscuits, heat 1 minute more.",
      "Press mixture into a baking tin.",
      "Refrigerate for at least 2 hours.",
    ],
  },
  8: {
    title: "Creamy one-pot tomato beef pasta 🍝",
    ingredients: [
      "750g ground beef",
      "500g pasta",
      "3 onions, chopped",
      "200ml single cream",
      "1200g tomato passata",
      "25g tomato puree",
      "1L hot vegetable stock",
      "90g grated parmesan",
      "2 tsp chili flakes",
      "4 tsp Italian seasoning",
      "Spinach to taste",
    ],
    instructions: [
      "Preheat oven to 180 degrees.",
      "Add cherry tomatoes, big tomatoes, red peppers and onions in oven dish with garlic on top.",
      "Drizzle olive oil and add herbs, bake 30 minutes.",
      "Cook pasta and fry minced beef.",
      "Blend roasted vegetables to a smooth sauce.",
      "Add cashew nuts, garlic paste, pesto and sambal and mix.",
      "Combine sauce with minced beef and serve with pasta.",
    ],
  },
  9: {
    title: "Apple-yoghurt cake 🍎",
    ingredients: [
      "125g oat flour",
      "125g almond flour",
      "Pinch of salt",
      "3 eggs",
      "70g honey",
      "230g yoghurt",
      "35g coconut oil",
      "2 tsp vanilla extract",
      "2 tsp cinnamon",
      "1 tsp baking powder",
      "1 tsp baking soda + lemon juice",
      "3 apples",
      "40g raisins",
      "2 tsp cinnamon",
      "1 tsp arrowroot + water",
      "Honey to taste",
      "1 tsp gingerbread spice",
    ],
    instructions: [
      "Preheat oven to 170 degrees.",
      "Mix all cake ingredients except apple filling until combined.",
      "Cut apples into small pieces.",
      "Fry apples with raisins, cinnamon, gingerbread spice and honey in a pan.",
      "Add arrowroot mixture to apples, cook until thickened.",
      "Add half apple mix to batter, pour into 20cm cake tin.",
      "Top with remaining apple mixture.",
      "Bake 60 minutes until toothpick clean.",
      "Cool completely before cutting.",
    ],
  },
  10: {
    title: "Pumpkin spiced cake 🎃",
    ingredients: [
      "170g oat flour",
      "100g plain Greek yoghurt",
      "100g honey",
      "80ml olive oil",
      "200g pumpkin puree",
      "2 eggs",
      "1 tsp baking powder",
      "1 tsp baking soda",
      "1 tsp cinnamon",
      "1 tsp vanilla extract",
      "1 tsp pumpkin spice",
    ],
    instructions: [
      "Preheat oven to 180 degrees.",
      "Line loaf pan with parchment paper.",
      "Blend all ingredients in a food processor until smooth.",
      "Pour batter into pan.",
      "Bake 45 minutes until golden brown and set.",
      "Cool before slicing.",
    ],
  },
  11: {
    title: "Sweet chili sauce 🌶️",
    ingredients: [
      "4 red peppers",
      "4 garlic cloves",
      "2 cm ginger",
      "2 tbsp soy sauce",
      "200 ml water",
      "2 tbsp cornstarch",
      "140g honey",
      "80 ml vinegar",
    ],
    instructions: [
      "Chop peppers, garlic and ginger in food processor.",
      "Heat water, soy sauce, honey and vinegar in pan over medium heat.",
      "Add pepper mixture, bring to boil, simmer 5 minutes.",
      "Mix cornstarch with water, add to pan, stir until thickened.",
      "Boil 1 minute more, cool before use.",
    ],
  },
  12: {
    title: "Almond cookies 🍪",
    ingredients: [
      "200g almond flour",
      "2 tbsp honey",
      "4 eggs",
      "2 tsp baking powder",
      "Pinch of salt",
      "1 tsp almond extract",
    ],
    instructions: [
      "Preheat oven to 180 degrees.",
      "Mix all ingredients and whisk until combined.",
      "Scoop 2 tbsp batter per cookie onto baking dish.",
      "Bake 9 minutes.",
      "Cool in refrigerator before eating.",
    ],
  },
  13: {
    title: "Almond cake 🎂",
    ingredients: [
      "200g almond flour",
      "190g all purpose flour",
      "3 tsp baking powder",
      "150g honey",
      "250g milk (optional dairy-free)",
      "85g olive oil",
      "2 tsp lemon zest",
      "2 tsp vanilla extract",
      "3 eggs",
    ],
    instructions: [
      "Preheat oven to 180 degrees.",
      "Mix all ingredients until smooth.",
      "Pour into lined baking tin.",
      "Bake 30 minutes until golden.",
      "Cool before serving.",
    ],
  },
  14: {
    title: "Creamy cashew pasta-sauce 🍝",
    ingredients: [
      "130g cashew nuts",
      "300ml water",
      "2 tbsp olive oil",
      "2 garlic cloves",
      "1 tbsp lemon juice",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Soak cashews in water for 30 minutes.",
      "Drain and blend cashews with water, olive oil, garlic and lemon juice until creamy.",
      "Heat sauce gently in pan.",
      "Season with salt and pepper.",
      "Serve with pasta.",
    ],
  },
  15: {
    title: "Healthy chocolate-peanut bites 🍫",
    ingredients: [
      "100g chocolate (optional dairy-free)",
      "100ml milk (optional plant based)",
      "Unsalted peanuts",
      "Honey (optional for sweetness)",
    ],
    instructions: [
      "Melt chocolate with milk in a saucepan over low heat.",
      "Mix in peanuts until coated.",
      "Add honey if desired for extra sweetness.",
      "Spoon mixture onto parchment paper and chill until set.",
    ],
  },
  16: {
    title: "Healthy apple pie 🍎",
    ingredients: [
      "5 small apples",
      "2 apples for topping",
      "175g honey",
      "1 tbsp cinnamon",
      "1 tsp vanilla extract",
      "1 tsp vanilla powder",
      "1 tsp honey",
      "3 eggs",
      "200g crème fraiche",
      "250g flour",
      "1 tbsp baking powder",
      "Optional almond paste for under apple top layer: mix 3 eggs, some honey and 120g almond flour",
    ],
    instructions: [
      "Preheat oven to 190 degrees.",
      "Cut 5 apples into small pieces and add to a bowl.",
      "Add 50g honey, cinnamon, vanilla extract, vanilla powder and 1 tsp honey to apples. Set aside.",
      "In another bowl, whisk 3 eggs and add remaining 125g honey, mix until thick and smooth.",
      "Add crème fraiche and mix again.",
      "Add flour and baking powder to egg mixture and mix.",
      "If using almond paste: scoop batter into baking tin and spread evenly.",
      "Add apple mixture on top.",
      "Spread almond paste evenly over apples.",
      "Add 2 topping apples on top and sprinkle with cinnamon.",
      "Bake for 60 minutes.",
      "If not using almond paste, keep 1/4 batter to spread on top of apples instead.",
    ],
  },
  17: {
    title: "Protein iced-coffee ☕️🧊",
    ingredients: [
      "100ml milk",
      "1 scoop protein powder vanilla flavour (e.g., @livepuri)",
      "1 espresso",
      "2 espresso-size small ice cubes",
      "4 regular small ice cubes",
      "Whipped cream (optional)",
      "Caramel drizzle (optional)",
    ],
    instructions: [
      "Add all ingredients into a food processor.",
      "Blend until smooth and thick.",
      "Add more ice cubes if needed for coldness.",
      "Serve and enjoy!",
    ],
  },
  18: {
    title: "Mango overnight oats 🥭",
    ingredients: [
      "1/2 mango",
      "4 tbsp oats",
      "2 tsp flax seeds",
      "2 tsp chia seeds",
      "1 scoop protein powder (any flavour)",
      "50ml milk (optional plant based)",
      "5 tbsp yoghurt",
      "1 tbsp honey",
    ],
    instructions: [
      "Mix protein powder, oats, chia seeds, flax seeds and milk in a bowl.",
      "In another bowl, mix yoghurt and honey.",
      "Add yoghurt mixture on top of oat mixture.",
      "Blend mango until smooth and add on top.",
      "Refrigerate overnight before eating.",
    ],
  },
  19: {
    title: "Chocolate banana muffins 🍫🍌",
    ingredients: [
      "2 bananas",
      "100g spelt flour",
      "40g cacao powder",
      "6g baking powder",
      "Pinch of salt",
      "100g honey",
      "60g melted butter",
      "1 egg",
      "1/2 tsp vanilla extract",
      "70g chocolate chips",
    ],
    instructions: [
      "Preheat oven to 170 degrees.",
      "Mix all ingredients except chocolate chips until smooth.",
      "Fold in chocolate chips.",
      "Scoop batter into muffin cases.",
      "Bake for around 20 minutes.",
      "For ganache: melt 50g dark chocolate with 50ml milk and drizzle on top (optional).",
    ],
  },
};
